version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - echo "Installing dependencies..."
      - npm install
      - npm install -g @angular/cli@9.1.15
  build:
    commands:
      - echo "Building Angular project..."
      - ng build --prod
  post_build:
    commands:
      - echo "Updating files in S3 bucket ..."
      - cd dist/covid/
      - ls -la
      - aws s3 sync . s3://dipankar-covid19tracker --delete
